name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  pipeline:
    uses: Shubhamsah27/Automated_Deployment/.github/workflows/deploy-reusable.yml@main
    with:
      app_name: pulseapi
      render_url: https://pulseapi-zu03.onrender.com
    secrets:
      RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
